version: "3"

networks:
  db:

services:
  api:
    build:
      context: .
      dockerfile: scripts/dev.Dockerfile
    volumes:
      - .:/go/src/github.com/factorycampus/radau
      - go_cache:/go/src
    environment:
      DEBUG: 1
      DB_HOST: db
      DB_USER: wifi
      DB_PASSWORD: wifi
      DB_DATABASE: wifi
      API_KEY_MANAGEMENT: pYWVcrR4DmgCfkfmEte5nGNW
      API_KEY_RADIUS: u39fNShDX6fAeXtWY6bZWY9x
      JWT_SECRET: $JWT_SECRET
    ports:
      - "8080:8080"
    networks:
      - db
  db:
    image: postgres:10
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db
    environment:
      POSTGRES_USER: wifi
      POSTGRES_PASSWORD: wifi
      POSTGRES_DB: wifi

volumes:
  db_data:
  go_cache: